### ISSUE TITLE
Auto-Caster has bugged power

### ISSUE THREAD

**Issue by jeridan** [drz2k/GS2#11]
On the official server (doesn't happen in single-player)

Crafted the basic auto-caster from thermal smeltery mod.  No power can be connected to it, the buffer appears bugged in it's gui as well.

![2017-10-01_20 28 44](https://user-images.githubusercontent.com/5779504/31061473-707aef44-a6e7-11e7-9c69-35c209f66e2b.png)
![2017-10-01_20 30 46](https://user-images.githubusercontent.com/5779504/31061474-707b7586-a6e7-11e7-8ed5-ff70bba5631d.png)

**Comment by ChetwyndKid** [comment]
Are you using Cryoducts?

**Comment by jeridan** [comment]
Those are redstone fluxducts.

**Comment by ChetwyndKid** [comment]
Hmmm thats odd. Might be an issue with Thermal, Can you try using Ender IO cables for me? 
And sorry never noticed the images the first time.

**Comment by jeridan** [comment]
Well the fluxducts and the conduits both connect and I see a value in the gui today.  Maybe last nights restart fixed it?

**Comment by ChetwyndKid** [comment]
I think its an issue with the conduits from Thermal. Fluxducts and Cryos, As we have had the issue in our place as well. Same with the Foundry blocks.

**Comment by drz2k** [comment]
I cant fix modproblems :( Report them to the moddev but its doubtfull they will fix it for 1.7
