### ISSUE TITLE
Disabled item craftable

### ISSUE THREAD

**Issue by welard** [drz2k/GS2#13]
Disabled item craftable when for the me blast resistant me drive

the item name and id
Disabled Item 4422:76
from ae2

when the chest is placed down it gives xray lol not sure what use that would be but have to tell :) see pic-builds

all so this item that is *(disabled Item) is all so required to make the quantum ring for access to your me  in other dims

**Comment by duncanwebb** [comment]
The Quantum ring is missing a ME Dense Cable - not sure why the ME Dense Cable has been disabled except if this has something to do with removing the ME Controller

**Comment by drz2k** [comment]
They are disabled by the mod because of channelless option. Added alternative recipe. Removed Cheatdrive
