### ISSUE TITLE
Spawner Controller

### ISSUE THREAD

**Issue by ChetwyndKid** [drz2k/GS2#14]
Looks like a few things from the Spawner Controller crash the server. (Maybe singleplayer too)

There is also the ability to spawn rockets. 

Might need to look through this and add some to the blacklist. 

Welard might be able to help you.

**Comment by welard** [comment]
if it was intended its stupid ley cheap to make if not i would say defo to ban out right
it need a unbroken spawn-er to work thoe witch was hard to figger out and i do blive you tryed to remove the item to move the spawners all ready  chaios dragon can be spawned ender dragon aswell 


@ChetwyndKid black listed one on the list for the crash anoth that will crash is 
Entity.BuildCraft:Robotics.bcRobot.name

**Comment by drz2k** [comment]
*jediwave* There has never been a spawner controller
