### ISSUE TITLE
Tinkers aluminum blocks

### ISSUE THREAD

**Issue by jeridan** [drz2k/GS2#15]
Tinkers aluminum blocks are not craft-able in the ore dictionary converter.

**Comment by torndar** [comment]
You can work around this by ore convert to tech reborn blocks -> craft to tech reborn ingots ->ore convert to tinkers ingots -> craft to tinkers blocks in the ore converter. It's a pain but it works for me. The other option is to use the Thermal metal caster instead of the foundry metal caster.

**Comment by Bennyboy1695** [comment]
If something isn't able to be done in the ore dictionary converter then its sometimes able to be done in a chisel

**Comment by drz2k** [comment]
Chisel it, if you really want aluminium blocks :)
