### ISSUE TITLE
Crystalize Quests Crash Game

### ISSUE THREAD

**Issue by duncanwebb** [drz2k/GS2#16]
Version 0.12h

I cannot select the tasks in the RF Submission Station, It always goes back to tungsten plating

![image](https://user-images.githubusercontent.com/4198031/31394378-73b3ca70-adde-11e7-9c06-b916f856cb0a.png)

If I select the Detect/Submit button the game crashes. I reckon the format error could be a cause.

![image](https://user-images.githubusercontent.com/4198031/31394458-a3ccbc08-adde-11e7-903d-5bfcf3a5bf20.png)

I'm also getting the following messages after restarting

![image](https://user-images.githubusercontent.com/4198031/31394532-d8aefb7a-adde-11e7-9a8b-969dbe7f7d9e.png)

**Comment by Bennyboy1695** [comment]
That error at the end should be in your log, if you could copy paste it to pastebin or something would help 😄

**Comment by duncanwebb** [comment]
Crashed here
[19:45:54] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception

Full log
https://www.dropbox.com/s/dhrolky5zvtf7vl/latest.log?dl=0

**Comment by duncanwebb** [comment]
Hi 
I'm sure that this should be selected and not return to the tungsten plating. This is what happens:
![galacticscience2-1](https://user-images.githubusercontent.com/4198031/31574295-c2e965aa-b0cc-11e7-9e88-cec1959c8224.gif)

**Comment by ZeroLyfe** [comment]
I'm having the same problem myself. Most of my quests available are rf submission quests and i can't do them because the quest submission station instantly reverts back to the tungsten plating quest when you try to select a different quest.

**Comment by drz2k** [comment]
The RF quests are very broken and will be replaced by a new mechanic soon.
