### ISSUE TITLE
Liquid energetic alloy very broken

### ISSUE THREAD

**Issue by duncanwebb** [drz2k/GS2#18]
Would it be possible to make liquid redstone when redstone is in the induction crucible furnace as it would make mixing liquid energetic alloy much easier to automate.

The recipe for molten energetic alloy seems incorrect.
1 gold ingot gives 108 mB liquid gold
1 gold ingot gives 144 mB molten gold
The recipe requires 48 mB or liquid gold or 36 mB of molten gold, they are the wrong way round. 
Would be better to make 72 mB with 72 mB of liquid gold, 50 mB of destabilized redstone and 125 mB of glowstone. as the 62 should be 62.5 and that leave 2 mB of glowstone so automation is difficult.

Sorry this is a bit complicated; the difference between liquid and molten metals took be a while to figure out.

**Comment by duncanwebb** [comment]
There is a second recipe for liquid energetic alloy using destabized redstone and liquid gold that I missed. The recipe should from NEI give 54mB of liquid alloy but only gives 36mB molten alloy and does not work every time, the alloy mixer tanks can be full and nothing is produced. 54mB liquid metal is half an ingot and 36mB molten is a quarter ingot.

**Comment by drz2k** [comment]
#24
