### ISSUE TITLE
Antimony ingots?

### ISSUE THREAD

**Issue by ZeroLyfe** [drz2k/GS2#19]
There doesn't seem to be a way to make the Antimony ingots needed to make the reinforced machine casing. I can make the antimony dust from tech reborn but it can't be smelted into an ingot. I'm unable to do the Warren Buffet quest because of this. I forgot to add this is version 0.12h

**Comment by welard** [comment]
try making the industrial blast furnace for smelting antimony ingots

**Comment by ZeroLyfe** [comment]
Ok I tried making the industrial blast furnace and it doesn't work for smelting the antimony either. Jei does not list any way of smelting the antimony dust into an ingot, it's also not listed in the recipe list on the industrial blast furnace and it can't even be placed into the redstone furnace. I tried /mt reload and I think the recipe has just been overlooked or accidently removed by the pack author.

**Comment by welard** [comment]
https://i.imgur.com/ksJvKdq.png

https://i.imgur.com/mgNmG5J.png

https://i.imgur.com/pTRLYQr.png

this is working it takes a wile just make sure you have 2 buckets of lava in the industrial blast furniss

**Comment by ZeroLyfe** [comment]
i have the blast furnace setup correctly, i'm only able to use standard machine casings in it right now. what version are you on? my antimony dust has a different nbt value of 5989:5 
https://imgur.com/a/f1FwS

**Comment by welard** [comment]
pic of your gui in the blast furniss?

**Comment by ZeroLyfe** [comment]
here is a pic in the blast furnace. the antimony has been in there over 24 hours. https://imgur.com/a/Ri11n

**Comment by welard** [comment]
yer you need the updated script to go forward and i cant help with that sorry

**Comment by ZeroLyfe** [comment]
well i just tried downloading a clean install of the pack and it still has the same problem with the nbt on the antimony being wrong and not having the recipe for the ingots in the game. I'm on the latest available version on the Twitch launcher 0.12h , i aslo downloaded and checked older versions of the game and they had the same problem as well. What version of the pack are you running welard?

**Comment by welard** [comment]
i am playing to the offshel server where we can talk with dev and help hime find things like this this was a over site a wile back and a patch was placed in to the server but but put of as a genrel relise we are hopeing there will be a update soon witch shuld have the fix in it

**Comment by drz2k** [comment]
Its fixed in the next build. Sorry for the delays ;)
