### ISSUE TITLE
I (torndar) crash the server when I try to connect.

### ISSUE THREAD

**Issue by torndar** [drz2k/GS2#2]
$subject

**Comment by ChetwyndKid** [comment]
I need you to try and join and give me a date and time off the crash with your timezone so I can find the log thank you.

**Comment by torndar** [comment]
4:24AM EDT (GMT-4)

**Comment by ChetwyndKid** [comment]
Currently looking into this, The light from one of your floodlights is misbehaving

**Comment by torndar** [comment]
Given all my gear is in a grave in a basement full of mobs if it's easier I'm fine with having my player data reset and the island wiped.

**Comment by ChetwyndKid** [comment]
Reset everything, Sorry about that not fully sure why that was happening. If it happens again let me know and I shall see what I can do.

**Comment by ChetwyndKid** [comment]
Fixed, Had a minor issue of database not deleting his island fully, But fixed and playing properly now.
