### ISSUE TITLE
jump boost?

### ISSUE THREAD

**Issue by MARINEBRAT** [drz2k/GS2#21]
so if you put a sign on a wall you cant normally jump on top of you can jump off the sign and continue vertical ascension.

**Comment by drz2k** [comment]
I have no idea what issue you have ...

**Comment by MARINEBRAT** [comment]
Seriously, maybe it's only on the server, but walk towards a wall with sign on it and hold down space bar. You'll jump on the signs.

**Comment by drz2k** [comment]
Well .. this is probably a GC mod issue then. And not really important, might even be a feature.
