### ISSUE TITLE
2mb energized glowstone leftover when making energetic alloy

### ISSUE THREAD

**Issue by CaddyWhumpusGamer** [drz2k/GS2#24]
When I use 1 glowstone +1 redstone + 1 gold ingot in a magma crucible and output to an alloy mixer I end up with 2mb of energized Glowstone left over after the mixing procces this stays in the alloy mixer and will eventually plug it up. this makes it very hard to automate the process and since the pack is all about automation I am sure this is some sort of bug caused by a mix-up on numbers during input.

**Comment by drz2k** [comment]
0.14
