### ISSUE TITLE
Bugged machines

### ISSUE THREAD

**Issue by Delightfullymadpanda** [drz2k/GS2#3]
In single player I've found that some machines won't do their intended jobs the ones i've found so far are

Furnace not smelting anything 
Auto sieve not accepting Moon turf  moon rock or moon dirt 

the only way I've found to fix this is by leaving single player and rejoining again but this fix only lasts about 5 minutes

**Comment by ChetwyndKid** [comment]
Oh? Care to explain what this some is and how it is bugged? :)

**Comment by Delightfullymadpanda** [comment]
sorry hit submit by accident :'D

**Comment by ChetwyndKid** [comment]
Could you explain how they are bugged?

**Comment by Delightfullymadpanda** [comment]
when i try to insert something like an uncooked crucible into a vanilla furnace it will just sit there and won't cook even if a fuel source has been inserted  this problem also applies to the auto sieve when i try and insert something by hand the item i try to sieve will just sit there even when the machine has power 


if it helps i could try and get a video of the problem and drop a google drive link here?

**Comment by ChetwyndKid** [comment]
This is odd, @drz2k do you know anything about this?

**Comment by Delightfullymadpanda** [comment]
it seems to be working now but if it bugs out again i'll be sure to record it and put it here but i also noticed that when it bugged out the recipes didn't appear in NEI either which i thought was weird i don't know if that helps or not

**Comment by Delightfullymadpanda** [comment]
here is a video of the bug with the sieve i also tried shift clicking the items into the sieve but it also didn't work


https://drive.google.com/file/d/0Bzh4LwO2QoLsTXdJSzNCYm4zVVU/view?usp=sharing

**Comment by drz2k** [comment]
![overview galactic science 2 modpacks projects minecraft curseforge 1](https://user-images.githubusercontent.com/3872527/30149683-d65f28d6-93a8-11e7-967a-9a8d54bbe601.png)

**Comment by ChetwyndKid** [comment]
Hey @Delightfullymadpanda is everything working after running that command?

**Comment by Delightfullymadpanda** [comment]
Oh sorry I never saw that you replied but I'll be sure to try it out later on I'm not at my own computer right now

**Comment by ChetwyndKid** [comment]
Alright, Let me know if it works or not.
