### ISSUE TITLE
Can't change quests in the RF submission station

### ISSUE THREAD

**Issue by torndar** [drz2k/GS2#7]
When trying to change quests in the RF submission station it changes briefly (network round trip it feels like) and then jumps back to the quest it initially displayed.

**Comment by drz2k** [comment]
SSP?

2017-09-22 2:21 GMT+02:00 torndar <notifications@github.com>:

**Comment by torndar** [comment]
SMP. Welard said the following on Discord.
"cath took the qb out of edit mode"
I don't know if that is why it's not working or something else but it's still not working today.

**Comment by ChetwyndKid** [comment]
I'm wanting to do a questbook progress reset to see if that fixes it.  But
caiths decision

**Comment by torndar** [comment]
The reset didn't help, is this still being investigated?

**Comment by drz2k** [comment]
RF Expansion has been removed.
