### ISSUE TITLE
Conflicting Recipies

### ISSUE THREAD

**Issue by ChetwyndKid** [drz2k/GS2#9]
Lumium Ingot can be created in the Synth but has the exact same same recipe as Lumium Dust, Which is causing issues with automation.

**Comment by duncanwebb** [comment]
Azure Bluet and Oxeye Daisy have the same minechem recipe.

**Comment by drz2k** [comment]
Lumium issue has resolved. The flowers have alot of overlapping recipes in mc. Wont fix them ;)
